# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow3(object):
    def setupUi(self, MainWindow3):
        MainWindow3.setObjectName("MainWindow3")
        MainWindow3.resize(1013, 481)
        MainWindow3.setMinimumSize(QtCore.QSize(1013, 481))
        MainWindow3.setMaximumSize(QtCore.QSize(1013, 481))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        MainWindow3.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow3)
        self.centralwidget.setObjectName("centralwidget")
        self.hak = QtWidgets.QLabel(self.centralwidget)
        self.hak.setGeometry(QtCore.QRect(30, 240, 111, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.hak.setFont(font)
        self.hak.setObjectName("hak")
        self.label_kelime = QtWidgets.QLabel(self.centralwidget)
        self.label_kelime.setGeometry(QtCore.QRect(30, 70, 951, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_kelime.setFont(font)
        self.label_kelime.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"background-color: rgb(170, 170, 255);")
        self.label_kelime.setText("")
        self.label_kelime.setObjectName("label_kelime")
        self.label_hak = QtWidgets.QLabel(self.centralwidget)
        self.label_hak.setGeometry(QtCore.QRect(160, 240, 61, 61))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_hak.setFont(font)
        self.label_hak.setText("")
        self.label_hak.setObjectName("label_hak")
        self.harf = QtWidgets.QLabel(self.centralwidget)
        self.harf.setGeometry(QtCore.QRect(30, 330, 111, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.harf.setFont(font)
        self.harf.setObjectName("harf")
        self.harf_line = QtWidgets.QLineEdit(self.centralwidget)
        self.harf_line.setGeometry(QtCore.QRect(160, 330, 61, 61))
        self.harf_line.setObjectName("harf_line")
        self.yaz_Button = QtWidgets.QPushButton(self.centralwidget)
        self.yaz_Button.setGeometry(QtCore.QRect(112, 420, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.yaz_Button.setFont(font)
        self.yaz_Button.setObjectName("yaz_Button")
        self.label_bilgi = QtWidgets.QLabel(self.centralwidget)
        self.label_bilgi.setGeometry(QtCore.QRect(700, 200, 281, 171))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_bilgi.setFont(font)
        self.label_bilgi.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"background-color: rgb(170, 170, 255);")
        self.label_bilgi.setText("")
        self.label_bilgi.setObjectName("label_bilgi")
        self.devam_Button = QtWidgets.QPushButton(self.centralwidget)
        self.devam_Button.setGeometry(QtCore.QRect(700, 420, 111, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.devam_Button.setFont(font)
        self.devam_Button.setObjectName("devam_Button")
        self.bitir_Button = QtWidgets.QPushButton(self.centralwidget)
        self.bitir_Button.setGeometry(QtCore.QRect(870, 420, 111, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bitir_Button.setFont(font)
        self.bitir_Button.setObjectName("bitir_Button")
        MainWindow3.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow3)
        self.statusbar.setObjectName("statusbar")
        MainWindow3.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow3)

    def retranslateUi(self, MainWindow3):
        _translate = QtCore.QCoreApplication.translate
        MainWindow3.setWindowTitle(_translate("MainWindow3", "WORD GAME"))
        self.hak.setText(_translate("MainWindow3", "HAK SAYISI"))
        self.harf.setText(_translate("MainWindow3", "HARF GİRİNİZ"))
        self.yaz_Button.setText(_translate("MainWindow3", "YAZ"))
        self.devam_Button.setText(_translate("MainWindow3", "DEVAM"))
        self.bitir_Button.setText(_translate("MainWindow3", "BİTİR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow3 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow3()
    ui.setupUi(MainWindow3)
    MainWindow3.show()
    sys.exit(app.exec_())
