# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/defne/OneDrive/Masaüstü/kelime_bulma\category.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(402, 233)
        MainWindow2.setMinimumSize(QtCore.QSize(402, 233))
        MainWindow2.setMaximumSize(QtCore.QSize(402, 233))
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.category = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.category.setFont(font)
        self.category.setObjectName("category")
        self.verticalLayout.addWidget(self.category)
        self.category_comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.category_comboBox.setFont(font)
        self.category_comboBox.setObjectName("category_comboBox")
        self.category_comboBox.addItem("")
        self.category_comboBox.addItem("")
        self.category_comboBox.addItem("")
        self.verticalLayout.addWidget(self.category_comboBox)
        self.length = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.length.setFont(font)
        self.length.setObjectName("length")
        self.verticalLayout.addWidget(self.length)
        self.lenght_line = QtWidgets.QLineEdit(self.centralwidget)
        self.lenght_line.setObjectName("lenght_line")
        self.verticalLayout.addWidget(self.lenght_line)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        MainWindow2.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow2)
        self.statusbar.setObjectName("statusbar")
        MainWindow2.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "WORD GAME"))
        self.category.setText(_translate("MainWindow2", "KATEGORİ"))
        self.category_comboBox.setItemText(0, _translate("MainWindow2", "Atasözü"))
        self.category_comboBox.setItemText(1, _translate("MainWindow2", "Deyim"))
        self.category_comboBox.setItemText(2, _translate("MainWindow2", "Kelime"))
        self.length.setText(_translate("MainWindow2", "UZUNLUK"))
        self.pushButton.setText(_translate("MainWindow2", "İLERİ"))
