# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/defne/OneDrive/Masaüstü/kelime_bulma\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow4(object):
    def setupUi(self, MainWindow4):
        MainWindow4.setObjectName("MainWindow4")
        MainWindow4.resize(350, 350)
        MainWindow4.setMinimumSize(QtCore.QSize(350, 350))
        MainWindow4.setMaximumSize(QtCore.QSize(400, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow4)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.mail = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.mail.setFont(font)
        self.mail.setObjectName("mail")
        self.verticalLayout.addWidget(self.mail)
        self.mail_line = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.mail_line.setFont(font)
        self.mail_line.setObjectName("mail_line")
        self.verticalLayout.addWidget(self.mail_line)
        self.sifre = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.sifre.setFont(font)
        self.sifre.setObjectName("sifre")
        self.verticalLayout.addWidget(self.sifre)
        self.sifre_line = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.sifre_line.setFont(font)
        self.sifre_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.sifre_line.setObjectName("sifre_line")
        self.verticalLayout.addWidget(self.sifre_line)
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.login_btn.setFont(font)
        self.login_btn.setObjectName("login_btn")
        self.verticalLayout.addWidget(self.login_btn)
        self.hesap_yoksa = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.hesap_yoksa.setFont(font)
        self.hesap_yoksa.setAlignment(QtCore.Qt.AlignCenter)
        self.hesap_yoksa.setObjectName("hesap_yoksa")
        self.verticalLayout.addWidget(self.hesap_yoksa)
        self.kayit_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.kayit_btn.setFont(font)
        self.kayit_btn.setObjectName("kayit_btn")
        self.verticalLayout.addWidget(self.kayit_btn)
        MainWindow4.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow4)
        self.statusbar.setObjectName("statusbar")
        MainWindow4.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow4)

    def retranslateUi(self, MainWindow4):
        _translate = QtCore.QCoreApplication.translate
        MainWindow4.setWindowTitle(_translate("MainWindow4", "MainWindow"))
        self.label.setText(_translate("MainWindow4", "WORD GAME"))
        self.mail.setText(_translate("MainWindow4", "MAİL ADRESİ"))
        self.sifre.setText(_translate("MainWindow4", "ŞİFRENİZ"))
        self.login_btn.setText(_translate("MainWindow4", "GİRİŞ YAP"))
        self.hesap_yoksa.setText(_translate("MainWindow4", "HESABINIZ YOKSA"))
        self.kayit_btn.setText(_translate("MainWindow4", "KAYIT OL"))
